module = "urdf_compose"
universal_dependency_path = [
    "poetry.lock",
    "pyproject.toml",
    "poetry_scripts.py",
    "setup.cfg",
    "../.github/workflows/urdf_compose_ci.yml",
]

[urdf_compose]
path = [
    "urdf_compose"
]
test_path = [
    "tests",
]
